FULL_NODE: true/false
    #true если на данном компьютере запущен FULL NODE сервис чиа, 
    #false если на данном компьютере запущен только харвестер чиа
T_REX: true/false
    #Если на компьютере запущен майнер T-Rex(GPU)
API_KEY_COINMARKETCUP: 606424d2-7082-4af8-a5fa-123456789123
    #бот берет актуальный курс чиа с https://coinmarketcap.com/ и переводит его в рубли, 
    #получите API_KEY на https://pro.coinmarketcap.com/signup, 
    #или пропишите в этой строке: "API_KEY_COINMARKETCUP: false" тогда бот будет показывать баланс только в чиа
TELEGRAM_BOT_TOKEN: 1651541335:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    #токен полученный от @BotFather
F_KEY: 12345.....аааа
    #Farmer public key чиа
POOL_KEY: xch.......aaaa
    #Pool public key чиа
PLOTLOGPATCH: /home/bds89/.chia/mainnet/plotter
    #путь где чиа хранит логи, мой бот будет складывать туда-же, 
    #таким образом, бот будет отображать прогресс засева, даже если вы сеете официальным клиентом чиа.
LOGPATCH: /home/bds89/.chia/mainnet/log/debug.log
    #путь где чиа хранит основные логи
PLOTS_FILE: /home/bds89/chia_tg_bot/chia_tg_bot/plots_file.sys
    #путь где бот будет хранить свой системный файл, лучше прописать по адресу бота 
    #(наверное мне стоит убрать это из конфига, но пока так)
WATCHDOG_LOG: /home/bds89/chia_tg_bot/chia_tg_bot/watchdog_log.txt
    #путь где бот будет хранить свой лог файл
CHAT_IDS: {}
    #словарь авторизованных CHAT_IDS телеграма, с которыми бот будет общаться, 
    #оставте пустым, после авторизации бот сам вас добавить
AUTO_P: true/false
    #автоматическое создание плотов, может быть включено позже из чата (кнопка "вкл автозасев"), 
    #для первого запуска оставьте пустым
NUM_PARALLEL_PLOTS: 1   
    #ограничение количества параллельных плотов к32. 
    #Выбирается исходя из многопоточности вашего компьютера и объема оперативной памяти. 
    #Если создается плот к33, бот считает его за два плота к32. Таким образом при заданном параметре "8" 
    #бот запустит засев 4х плотов к33. 
    #Может быть изменено из чата командой /parallel_plots
COMPUTING_TABLE: 1   
    #таблица первой фазы засева, на которой бот начнет засев следующего плота. Значения от 1 до 7. 
    #Если оставить значение "1" бот начнет сеять все плоты одновременно (при условии наличия свободных дисков). 
    #Параметр необходим для распределения ресурсов компьютера, т.к. в первой и второй фазах потребление ресурсов максимальное. 
    #Может быть изменено из чата командой /table
MIN_DISK_TOTAL: 1100   
    #минимальный размер диска в вашей системе(GiB), на которые бот обращает внимание. 
    #Например если ваши NVME 1Тб и вы не хотите что-бы бот на них размещал плоты, следует оставить этот параметр "1100".
MIN_DISK_FREE: 109   
    #минимальное свободное место(GiB) на дисках в вашей системе, на которые бот обращает внимание. 
    #Пока актуальны плоты к32, оставьте значение "109"
SATA_AS_SSD: true/false   
    #использовать SATA диски для создания плотов. Рекомендую оставить "true", 
    #в таком случае бот в первую очередь будет использовать диски, путь к корню которых       
    #содержит "SATA" в любом регистре (например /mnt/Sata21), не испольуя ресурс SSD. 
    #Может быть изменено из чата командой /set_plot_config
USE_K33: 'yes'/'no'   
    #при включенном параметре бот будет засеевать диски оптимальным количеством плотов к32 и к33, 
    #оставляя наименьшее количество свободного места. При выключенном, будут сеятся только плоты к32. 
    #Может быть изменено из чата командой /set_plot_config
DEPTH: 2   
    #глубина рекурсивного поиска плотов на диске и его подкаталогах. 
    #Бот сеет всегда в корень диска, создавая там папки /plots и /temp, для этого случая достаточно значения этого параметра "1", 
    #но если ваши плоты лежат где-то глубже, увеличьте этот параметр. 
    #Если на диске большое количество подкаталогов, увеличение этого параметра может привести к задержкам в работе.
SSD:
  /mnt/ssd2: /mnt/ssd2
  /home/bds89/work: /
    #словарь ваших SSD/NVME используемых для создания плотов. Ключи(слева) это путь, в котором бот будет создавать /temp папку для засева, 
    #значения(справа) это путь к корню ваших SSD/NVME (необходим для определения свободного места). 
    #Если параметр "USE_K33: 'no'"  бот будет использовать для засева только диски, указанные в этом словаре.
SUDO_PASS: '0'   
    #пароль суперпользователя в вашей системе. Необходим для получения S.M.A.R.T информации о ваших дисках. 
    #Если не доверяете боту, можете оставить пустой строкой в кавычках: SUDO_PASS: ''
WD_INTERVAL: 300   
    #периодичность (сек) опроса ботом статуса фермы чиа и кошелька, для контроля состояния и уведомления об изменении. 
    #Значение "0" отключает опросы и контроль состояния. Может быть изменено из чата командой /wd
FULL_NODE_PORT: 2605   
    #порт на котором FULL_NODE запускает сокет для принятия сообщений от харвестеров
HARVESTER_PORT: 2606   
    #порт на котором харвестер запускает сокет для принятия команд от FULL_NODE
NODE_LIST:
  1: 192.168.0.101
  2: 192.168.0.102
    #словарь ваших компьютеров в ферме. Ключи(слева) целое число, набрав которое боту в любом диалоге, 
    #он переключит вас на соответствующий компьютер, значения(справа) IP адрес компьютера. 
    #ВНИМАНИЕ: Ключ "1" должен быть всегда с адресом вашего FULL NODE. 
    #Если у вас нету сети харвестеров, и вы используете один компьютер оставьте словарь пустым: "NODE_LIST: {}"
HARVESTER_MAC:
- ECFA5CEFADB1
- ECFA5CEFADB0
    #список MAC адресов ваших харвестеров, на которые будут отправлены пакеты WakeOnLAN при запуске бота на FULL_NODE. 
    #Если харвестеров нет, либо вы не хотите включать их таким образом оставте параметр пустым: "HARVESTER_MAC: false"
PASSWORD: '0'   
    #задайте пароль вашему боту, который потребуется для авторизации вас после команды /start
LANGUAGE: english
SSD_DEVICES:
  System disk: /dev/sdb2
  Dop disk: /dev/sda1
    #словарь ваших дисков, о которых необходимо получать информацию при нажатии кнопки SSD info. 
    #Ключи(слева) имя диска отображаемое в чате, значения(справа) обозначение устройства в системе, 
    #можно посмотреть в системном мониторе на вкладке файловые системы
 CRITICAL_PARAMS:
  SSD_temperature: 65
  HDD_temperature: 45
  CPU_temperature: 80
  USED_RAM%: 95
  GPU_temperature: 70
    #Бот пришлет уведоление всем в чате, при превышении данных порогов по температурам и использованию оперативной памяти в процентах
#Следующие параметры можно удалить:
T_REX: false
	#Используется ли майнер T_REX
BINANCE_KEY: 1111
BINANCE_SECRET: 1111
OKEX_KEY: 1111
OKEX_SECRET: 1111
OKEX_PASS: 1111
	#Ключи от бирж, для просмотра балансов
MQTT:
  TOPICS:
    bletrecker/sensor/temperature_room/state: 'Температура на балконе'
    bletrecker/sensor/humidity_room/state: 'Влажность на балконе'
  HOSTNAME: 192.168.0.120
  USERNAME: bds89
  PASS: Bodal2605%
	#Данне MQTT для отображения, например температура в комнате с фермой
